### ISSUE TITLE
keeps suggesting the same words (they don't even solve the prompt)

### ISSUE THREAD

**Issue by bl1ndfate** [nicolaspiet/jklm-word-bot#5]
![image](https://user-images.githubusercontent.com/130220099/230716523-6f37a818-8d67-4057-9f4f-406cb2e484c6.png)
countercountermeasure(s) has not successfully solved any of the 19 given prompts. why is it doing this?

**Comment by nicolaspiet** [comment]
I don't know what's going on.
I've tested it in a few games and I'm not having that problem.

The only possible reason I see is that the program only finds this word that matches the syllable.

**Comment by nicolaspiet** [comment]
fixed, it never writes the same words more than one time.
